name: Ejecutar Script SUNAT

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest  # Necesitas Windows porque usas EdgeDriver
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          pip install selenium
          pip install beautifulsoup4
          pip install webdriver-manager

      - name: Ejecutar script
        run: python exchangebot_sunat_v2.py
